name: Deploy to GitHub Pages

on:
  schedule:
    # Run daily at 6 AM UTC (adjust timezone as needed)
    - cron: "0 6 * * *"
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jinja2

      - name: Create credentials file
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > credentials.json
          # Verify the credentials file is not empty
          if [ ! -s credentials.json ]; then
            echo "❌ Error: GOOGLE_CREDENTIALS_JSON secret is empty or not set!"
            echo "Please add your Google service account credentials to GitHub secrets."
            exit 1
          fi
          echo "✅ Credentials file created successfully"

      - name: Create .env file
        run: |
          echo "TELEGRAM_API_ID=${{ secrets.TELEGRAM_API_ID }}" >> .env
          echo "TELEGRAM_API_HASH=${{ secrets.TELEGRAM_API_HASH }}" >> .env
          echo "PHONE_NUMBER=${{ secrets.PHONE_NUMBER }}" >> .env
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
          echo "GOOGLE_SHEETS_CREDS=credentials.json" >> .env

          # Verify required secrets are set
          if [ -z "${{ secrets.TELEGRAM_API_ID }}" ]; then
            echo "❌ Error: TELEGRAM_API_ID secret is not set!"
            exit 1
          fi
          if [ -z "${{ secrets.TELEGRAM_API_HASH }}" ]; then
            echo "❌ Error: TELEGRAM_API_HASH secret is not set!"
            exit 1
          fi
          if [ -z "${{ secrets.PHONE_NUMBER }}" ]; then
            echo "❌ Error: PHONE_NUMBER secret is not set!"
            exit 1
          fi
          echo "✅ Environment variables created successfully"

      - name: Generate static site
        run: |
          python generate_static_site.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          cname: job.harshsingh.io
